config/routes.rb
Katpark::Application.routes.draw do
  root to: "home#index"
  get "/about" => "home#about", as: :about

  devise_for :admins

  namespace :admin do
    root to: "posts#index"
    resources :posts
    resources :images
    resources :admins
    get "/edit_password/:id" => "admins#edit_password", as: :edit_password
    put "/edit_password/:id" => "admins#update_password", as: :update_password
  end

  devise_scope :admin do
    get "/login" => "devise/sessions#new"
  end

  resources :posts, only: [:show, :index]
  resources :contacts, only: [:new, :create]

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_many :posts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def to_s
    "#{self.name}"
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :city, :email, :message, :name, :phone_number

  validates :city, :email, :message, :name, :phone_number, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  VALID_PHONE_REGEX = /\A\+?\d?-?\(?\d{3}\)?-?\d{3}-?\d{4}\z/
  validates :phone_number, format: { with: VALID_PHONE_REGEX }
end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :avatar
  has_attached_file :avatar, styles: { meduim: "300x300>", thumb: "100x100>" }

  validates :avatar, presence: true
  validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/png", "image/gif"] }
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_save :slugify

  belongs_to :author, class_name: "Admin"

  attr_accessible :body, :title, :featured, :author_id

  validates :body, presence: true
  validates :title, presence: true
  validates :title, uniqueness: true

  scope :featured, where(featured: true).order("created_at DESC").limit(1)

  def slugify
    self.slug = self.title.gsub(/[[:punct:]\|\+\^\$=~`<>]+/, "").parameterize
  end

  def to_param
    self.slug
  end
end

app/models/style_seat.rb
class StyleSeat < ActiveRecord::Base
  attr_accessible :city, :state, :street_address, :title, :zip_code, :phone_number
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < Admin::BaseController
  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin.find(params[:id])
    if @admin.update_attributes(params[:admin])
      flash[:notice] = "Your profile was updated successfully."
      redirect_to admin_root_path
    else
      flash[:alert] = "There was an error updating your profile."
      render "edit"
    end
  end

  def edit_password
    @admin = Admin.find(params[:id])
  end

  def update_password
    @admin = Admin.find(params[:id])
    if @admin.update_with_password(params[:admin])
      flash[:notice] = "Your password was updated successfully."
      sign_in @admin, :bypass => true
      redirect_to admin_root_path
    else
      flash[:alert] = "There was an error updating your password."
      render "edit_password"
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_admin!
  layout "admin"
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  def index
    @images = Image.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @image = Image.new
    respond_to do |format|
      format.html
      format.js # add this line for your js template
    end
  end

  def new
  end

  def create
    @images = Image.all
    @image = Image.new(params[:image])
    if @image.save
      flash[:notice] = "Image has been uploaded."
      redirect_to admin_images_path
    else
      flash[:alert] = "There was a problem uploading the image." +
        " Error - Image #{@image.errors.messages.values[0][0]}"
      redirect_to admin_images_path
    end
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.avatar.destroy
      @image.destroy
      flash[:notice] = "Image has been deleted."
      redirect_to admin_images_path
    else
      flash[:alert] = "There was a problem deleting the image."
      redirect_to admin_images_path
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :find_post, only: [:show, :edit, :update, :destroy]
  before_filter :get_admins, only: [:new, :create, :edit, :update]

  def index
    @posts = Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
    @post = Post.new
    @images = Image.order('created_at DESC').limit(5)
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:notice] = "New post created successfully."
      redirect_to admin_root_path
    else
      flash[:alert] = "There was an error creating your post."
      render "new"
    end
  end

  def edit
    @images = Image.order('created_at DESC').limit(5)
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post updated successfully."
      redirect_to admin_root_path
    else
      flash[:alert] = "There was an error updating your post."
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post was deleted."
    redirect_to admin_root_path
  end

  private
  def find_post
    @post = Post.find_by_slug(params[:id])
  end

  def get_admins
    @admins = Admin.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @style_seat = StyleSeat.first
  end

  def create
    @style_seat = StyleSeat.first
    @contact = Contact.new(params[:contact])
    if @contact.save
      # ContactMailer.delay.new_message(@contact)
      ContactMailer.new_message(@contact).deliver
      flash[:notice] = "Your message has been sent."
      redirect_to new_contact_path
    else
      flash[:alert] = "There was an error sending your message."
      render "new"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @featured = Post.featured.first
  end

  def about
    @style_seat = StyleSeat.first
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @post = Post.find_by_slug(params[:id])
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
  def remove_ext(file)
    file.gsub(/\.[^.]+$/, "")
  end
end

app/helpers/application_helper.rb
require 'redcarpet'
module ApplicationHelper
  def markdown(text)
    markdown_options = { autolink: true, space_after_headers: true }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, markdown_options)
    markdown.render(text)
  end

  def gravatar(email, size)
    hash = Digest::MD5.hexdigest(email.downcase)
    "http://www.gravatar.com/avatar/#{hash}?s=#{size.to_s}"
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/_side_nav.html.erb
<div class="large-2 columns">
  <ul class="side-nav">
    <li><h4><%= link_to "Posts", admin_posts_path %></h4></li>
    <li><h4><%= link_to "New Post", new_admin_post_path %></h4></li>
    <li class="divider"></li>
    <li><h4><%= link_to "Images", admin_images_path %></h4></li>
    <li class="divider"></li>
    <li><h4><%= link_to "Profile", edit_admin_admin_path(current_admin) %></h4></li>
  </ul>
</div>

app/views/admin/admins/edit.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= form_for [:admin, @admin] do |f| %>
      <p>Gravatar<br>
      <%= image_tag gravatar(@admin.email, 100) %></p>
      <%= f.email_field :email %>
      <%= f.text_field :name %>
      <%= f.submit "Submit", :disable_with => 'Submiting...', class: "button" %>
    <% end %>
  </div>
</div>
<%= link_to "Change Password", admin_edit_password_path(current_admin) %>

app/views/admin/admins/edit_password.html.erb
<div class="row">
  <div class="large-6 columns">
    <h3>Change Password</h3>
    <%= form_for [:admin, @admin], url: admin_update_password_path, method: "put" do |f| %>
      <%= f.password_field :current_password, label: "Current Password" %>
      <%= f.password_field :password, label: "New Password", :autocomplete => "off" %>
      <%= f.password_field :password_confirmation, label: "New Password Confirmation" %>
      <%= f.submit "Submit", :disable_with => 'Submiting...', class: "button" %>
    <% end %>
  </div>
</div>

app/views/admin/images/_image.html.erb
    <tr>
      <td><%= image.avatar_file_name %></td>
      <td><%= image.avatar_content_type %></td>
      <td><%= number_to_human_size(image.avatar_file_size) %></td>
      <td><%= image_tag image.avatar.url(:thumb) %></td>
      <td><%= link_to "Delete", admin_image_path(image), method: "delete", confirm: "Are you sure?", class: "button small alert round" %></td>
    </tr>

app/views/admin/images/index.html.erb
<%= form_for [:admin, @image] do |f| %>
  <%= f.label :avatar, "Image #1" %>
  <%= f.file_field :avatar, label: false %>
  <%= f.submit "Upload Image", :disable_with => 'Uploading Image...', class: "button" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Image Name</th>
      <th>Image Type</th>
      <th>Image Size</th>
      <th>Image</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @images %>
  </tbody>
</table>
<% unless @images.blank? %>
  <%= will_paginate @images %>
<% end %>

app/views/admin/images/index.js.erb
$('tbody').append('<%= j render(@images) %>');
<% if @images.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@images) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/posts/_form.html.erb
<div class="large-8 columns">
  <%= form_for [:admin, @post], html: { class: "nice custom" } do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :body, size: "0x20", class: "post" %>
    <div class="row">
      <div class="large-6 columns">
        <%= f.label :author_id, "Author" %>
        <%= f.collection_select :author_id, @admins, :id, :name %>
      </div>
    </div>
    <%= f.check_box :featured, label: " Featured" %><br>
    <%= f.submit :disable_with => 'Submiting Post...', class: "button" %>
  <% end %>
</div>

app/views/admin/posts/_imagepicker.html.erb
<div class="large-4 columns">
  <h4>Images</h4>
    <table class="table-scroll">
      <tbody>
        <% if @images %>
          <% @images.each do |image| %>
            <tr>
              <td><%= image_tag image.avatar.url(:thumb) %></td>
              <td><a class="add-image button" href="#" data-image-name="<%= remove_ext(image.avatar_file_name) %>" data-image-url="<%= image.avatar.url %>">Add Image</a></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/admin/posts/_post.html.erb
<article>
  <h2><%= post.title %></h2>
  <p>Author: <%= post.author %></p>
  <p><%== markdown(post.body).truncate(300) %></p>
  <%= link_to "Edit", edit_admin_post_path(post), class: "button small secondary" %>
  <%= link_to "Delete", admin_post_path(post), method: "delete", confirm: "Are you sure?", class: "button small alert" %>
</article>
<hr>

app/views/admin/posts/edit.html.erb
<div class="row">
  <%= render 'form' %>
  <%= render 'imagepicker' %>
</div>

app/views/admin/posts/index.html.erb
<%= render @posts %>
<div class="admin-pagination">
  <% if @posts.previous_page %>
    <%= link_to params.merge(:page => @posts.previous_page ), class: "admin-previous_page button small round"  do %>
      <i class="icon-hand-left"></i> Previous
    <% end %>
  <% end %>
  <% if @posts.next_page %>
    <%= link_to params.merge(:page => @posts.next_page ), class: "admin-next_page button small round" do %>
      Next <i class="icon-hand-right"></i>
    <% end %>
  <% end %>
</div>

app/views/admin/posts/new.html.erb
<div class="row">
  <%= render 'form' %>
  <%= render 'imagepicker' %>
</div>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p>Find me in app/views/admin/posts/show.html.erb</p>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<%= render 'layouts/page_title' %>
<div class="row">
  <div class="large-8 columns border baby">
    <%= form_for @contact do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :email %>
      <%= f.text_field :city %>
      <%= f.text_field :phone_number %>
      <%= f.text_area :message %>
      <%= f.submit "Submit", :disable_with => 'Submiting...', class: "button" %>
    <% end %>
  </div>
  <div class="large-3 large-offset-1 columns border lav">
    <div class="row">
      <div class="large-12 small-10 large-centered small-centered columns">
        <img src="<%= @style_seat.image %>">
        <h5><%= @style_seat.title %></h5>
        <p><%= @style_seat.street_address %></p>
        <p><%= "#{@style_seat.city}, #{@style_seat.state} #{@style_seat.zip_code}" %></p>
        <!-- <img src="http://maps.googleapis.com/maps/api/staticmap?size=400x300&center=Salon+Gisele,Villa+Park,CA&zoom=15&maptype=roadmap&markers=color:purple%7CSalon+Gisele,Villa+Park,CA&sensor=false&scale=2" /> -->
        <p><%= @style_seat.phone_number %></p>
        <a href="https://www.styleseat.com/katpark" class="button">Book Me</a>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<% provide(:title, 'About') %>
<%= render 'layouts/page_title' %>
<div class="row">
  <div id="about" class="large-12 columns blush">
    <%= image_tag @style_seat.image %>
    <p>
      <span class="big-letter">K</span>at Park is a Southern California based hair and makeup artist. She is a licensed Cosmetologist and has been making people beautiful for about 8 years.
    </p>
    <p>
      <span class="big-letter">W</span>ith a degree from FIDM, she uses her fashion flare to create Bridal accessories as well. Weddings are her forte and she loves making brides and loved ones feel perfect! Meeting new and exciting people is what makes her love what she does! <%= link_to "Contact", new_contact_path %> Kat Park for more info.
    </p>
  </div>
</div>

app/views/home/index.html.erb
<% provide(:title, 'Welcome') %>
<div class="row">
  <div class="large-12 columns border lav">
    <div class="slideshow-wrapper">
      <div class="preloader"></div>
      <ul data-orbit>
        <li>
          <img src="http://placekitten.com/g/1000/500" />
          <div class="orbit-caption">Amazing</div>
        </li>
        <li>
          <img src="http://placekitten.com/g/1000/500" />
          <div class="orbit-caption">Beautiful</div>
        </li>
        <li>
          <img src="http://placekitten.com/g/1000/500" />
          <div class="orbit-caption">Pretty</div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-4 columns border blush">
    <% if @featured %>
      <h4><%= link_to @featured.title, post_path(@featured) %></h4>
      <p>
        <%== markdown(@featured.body.truncate(250)) %>
      </p>
    <% end %>
  </div>
  <div id="instacontainer" class="large-7 large-offset-1 columns border baby">
    <h4>#katpark</h4>
    <ul class="instagram small-block-grid-3"></ul>
  </div>
</div>

<%= content_for :instagramjs do %>
  <script>
    jQuery(function($) {
      $('.instagram').on('willLoadInstagram', function(event, options) {
        $("#instacontainer").append("<div id='loading'><i class='icon-heart icon-spin icon-4x'></i><br><br>Loading...</div>");
      });
      $('.instagram').on('didLoadInstagram', function(event, response) {
        $("#loading").fadeOut('slow', function() {
          $(this).remove();
        });
        $.each(response.data, function(index, value) {
         $('.instagram').append("<li><a target='_blank' href='" + this.link + "'><img src='" + this.images.thumbnail.url + "' /></a></li>").hide().fadeIn("slow");
        });
      });
      $('.instagram').instagram({
        hash: 'katpark',
        count: 6,
        clientId: 'c3901ab170794c17a0c29c77a565c23a'
      });
    });
  </script>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div data-alert class="alert-box success">
    <%= flash[:notice] %>
   <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:alert] %>
  <div data-alert class="alert-box alert">
    <%= flash[:alert] %>
   <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="top-footer">
    <div class="row">
      <div style="" class="top-footer large-6 large-centered columns">
        <span class="icon-stack">
          <a target="_blank" href="http://instagram.com/katpark/">
            <i class="icon-circle icon-2x icon-stack-base"></i>
            <i class="icon-instagram icon-2x icon-dark"></i>
          </a>
        </span>
        <span class="icon-stack">
          <a target="_blank" href="https://www.facebook.com/katparkbeauty">
            <i class="icon-circle icon-2x icon-stack-base"></i>
            <i class="icon-facebook icon-2x icon-dark"></i>
          </a>
        </span>
        <span class="icon-stack">
          <a target="_blank" href="https://twitter.com/katpark">
            <i class="icon-circle icon-2x icon-stack-base"></i>
            <i class="icon-twitter icon-2x icon-dark"></i>
          </a>
        </span>
        <span class="icon-stack">
          <a target="_blank" href="http://pinterest.com/katpark/">
            <i class="icon-circle icon-2x icon-stack-base"></i>
            <i class="icon-pinterest icon-2x icon-dark"></i>
          </a>
        </span>
      </div>
    </div>
  </div>
  <div class="bottom-footer">
    <div class="row">
      <div style="" class="bottom-footer large-6 large-centered columns">
        &copy; 2013 Kat Park &reg;, LLC. All Rights Reserved.
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1>
          <%= link_to root_path  do %>
            kat park
            <%= image_tag "kp_logo_thick_white_border_65x65.png" %>
          <% end %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <li class="divider"></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <li class="divider"></li>
        <li><%= link_to "About", about_path %></li>
        <li class="divider"></li>
        <% if admin_signed_in? %>
          <li class="has-dropdown"><a href="#"><%= current_admin.email %></a>
            <ul class="dropdown">
              <li><%= link_to admin_root_path do %>
                  <i class="icon-dashboard"></i> Dashboard
                <% end %></li>
              <li><%= link_to edit_admin_admin_path(current_admin) do %>
                <i class="icon-user"></i> Profile
              <% end %></li>
              <li><%= link_to  destroy_admin_session_path, method: "delete" do %>
                <i class="icon-signout"></i> Sign Out
              <% end %></li>
            </ul>
          </li>
          <li class="divider"></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/_page_title.html.erb
<div class="row">
  <div class="large-12 columns"><h2 class="page-title"><%= yield(:title) %></h2></div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Admin" %></title>

    <%= stylesheet_link_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Podkova|Raleway:300' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render partial: 'layouts/flash', locals: { flash: flash } %>
      <%= render 'layouts/nav' %>
    </header>
    <div class="row">
      <%= render 'admin/side_nav' %>
      <div class="large-10 columns">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<!--
      ___           ___           ___           ___           ___           ___           ___
     /\__\         /\  \         /\  \         /\  \         /\  \         /\  \         /\__\
    /:/  /        /::\  \        \:\  \       /::\  \       /::\  \       /::\  \       /:/  /
   /:/__/        /:/\:\  \        \:\  \     /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/__/
  /::\__\____   /::\~\:\  \       /::\  \   /::\~\:\  \   /::\~\:\  \   /::\~\:\  \   /::\__\____
 /:/\:::::\__\ /:/\:\ \:\__\     /:/\:\__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/\:::::\__\
 \/_|:|~~|~    \/__\:\/:/  /    /:/  \/__/ \/__\:\/:/  / \/__\:\/:/  / \/_|::\/:/  / \/_|:|~~|~
    |:|  |          \::/  /    /:/  /           \::/  /       \::/  /     |:|::/  /     |:|  |
    |:|  |          /:/  /     \/__/             \/__/        /:/  /      |:|\/__/      |:|  |
    |:|  |         /:/  /                                    /:/  /       |:|  |        |:|  |
     \|__|         \/__/                                     \/__/         \|__|         \|__|

                        Made by Jeff Horn with love. - jeffreyhorn.com
-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>kat park | <%= content_for?(:title) ? yield(:title) : "Welcome" %></title>

  	<%= stylesheet_link_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Podkova|Raleway:300' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= content_for :fbjs %>
    <header>
      <%= render partial: 'layouts/flash', locals: { flash: flash } %>
      <%= render 'layouts/nav' %>
    </header>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
    <%= content_for :instagramjs %>
    <%= content_for :postjs %>
  </body>
</html>

app/views/posts/_disqus-comments.html.erb
<script id="disqus-comments" type="text/javascript">
  /* * * Hi CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'devkatpark'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = '//' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());
</script>

app/views/posts/_pagination.html.erb
<div class="pagination">
  <% if @posts.previous_page %>
    <%= link_to params.merge(:page => @posts.previous_page ), class: "previous_page button small round"  do %>
      <i class="icon-hand-left"></i> Previous
    <% end %>
  <% end %>
  <% if @posts.next_page %>
    <%= link_to params.merge(:page => @posts.next_page ), class: "next_page button small round" do %>
      Next <i class="icon-hand-right"></i>
    <% end %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<article class="<%= cycle("lav", "baby", "blush") %>">
  <h2 class="post-title"><%= link_to post.title, post_path(post) %></h2>
  <%= render partial: 'posts/post_info', locals: { post: post} %>
  <p><%== markdown(post.body).truncate(140) %></p>
  <%= link_to post_path(post.slug), class:"read-more" do %>
    Read More <i class="icon-arrow-right"></i>
  <% end %>
</article>

app/views/posts/_post_info.html.erb
<div class="row">
  <div class="large-5 columns">
    <div class="row">
      <div class="small-4 columns">
        <%= image_tag gravatar(post.author.email, 100) %>
      </div>
      <div class="small-8 columns">
        <ul class="post-info">
          <li>
            <i class="icon-user"></i>
             <%= post.author %>
          </li>
          <li>
            <i class="icon-calendar"></i>
             <%= post.created_at.strftime('%b %d, %Y') %>
          </li>
          <li>
            <i class="icon-comment"></i>
             <%= link_to "", "#{post_path(post.slug)}#disqus_thread", class: "disqus-comment-count" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>